"""fxi imageline mode

Revision ID: 47daf7dba8ba
Revises: b8e0057d91b6
Create Date: 2024-08-02 16:14:35.986981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47daf7dba8ba'
down_revision: Union[str, None] = 'b8e0057d91b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
