"""add usertype

Revision ID: ed1797f5ea1f
Revises: 01fcca8e14da
Create Date: 2024-08-02 16:10:29.391497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1797f5ea1f'
down_revision: Union[str, None] = '01fcca8e14da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usertype', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'usertype')
    # ### end Alembic commands ###
