"""
This type stub file was generated by pyright.
"""

from fasthtml.core import *
from fasthtml.starlette import *

auth_hdrs = ...
class BasicAuthMiddleware(MiddlewareBase):
    def __init__(self, app, cb, skip=...) -> None:
        ...
    
    async def __call__(self, scope, receive, send) -> None:
        ...
    
    async def authenticate(self, conn): # -> str | None:
        ...
    


def user_pwd_auth(lookup=..., skip=..., **kwargs): # -> Middleware:
    ...

def basic_logout(request): # -> str:
    ...

