"""
This type stub file was generated by pyright.
"""

from fastcore.utils import *
from fastcore.script import bool_arg, call_parse

__all__ = ['railway_link', 'railway_deploy']
@call_parse
def railway_link(): # -> None:
    "Link the current directory to the current project's Railway service"
    ...

@call_parse
def railway_deploy(name: str, mount: bool_arg = ...): # -> None:
    """Deploy a FastHTML app to Railway"""
    ...

