"""
This type stub file was generated by pyright.
"""

from fastcore.utils import *
from fastlite import *
from .basics import *
from .starlette import *

__all__ = ['fast_app', 'ContainerX', 'PageX']
def fast_app(db_file: Optional[str] = ..., render: Optional[callable] = ..., hdrs: Optional[tuple] = ..., ftrs: Optional[tuple] = ..., tbls: Optional[dict] = ..., before: Optional[tuple] | Beforeware = ..., middleware: Optional[tuple] = ..., live: bool = ..., debug: bool = ..., routes: Optional[tuple] = ..., exception_handlers: Optional[dict] = ..., on_startup: Optional[callable] = ..., on_shutdown: Optional[callable] = ..., lifespan: Optional[callable] = ..., default_hdrs=..., pico: Optional[bool] = ..., surreal: Optional[bool] = ..., htmx: Optional[bool] = ..., ws_hdr: bool = ..., secret_key: Optional[str] = ..., key_fname: str = ..., session_cookie: str = ..., max_age: int = ..., sess_path: str = ..., same_site: str = ..., sess_https_only: bool = ..., sess_domain: Optional[str] = ..., htmlkw: Optional[dict] = ..., bodykw: Optional[dict] = ..., reload_attempts: Optional[int] = ..., reload_interval: Optional[int] = ..., **kwargs) -> Any:
    "Create a FastHTML or FastHTMLWithLiveReload app."
    ...

def ContainerX(*cs, **kwargs):
    ...

def PageX(title, *con): # -> tuple[Any, Any]:
    ...

