"""
This type stub file was generated by pyright.
"""

from fastcore.utils import *
from fasthtml.components import *
from fasthtml.xtend import *

__all__ = ['marked_imp', 'npmcdn', 'light_media', 'dark_media', 'MarkdownJS', 'KatexMarkdownJS', 'HighlightJS', 'SortableJS']
def light_media(css: str): # -> FT:
    "Render light media for day mode views"
    ...

def dark_media(css: str): # -> FT:
    "Render dark media for nught mode views"
    ...

marked_imp = ...
npmcdn = ...
def MarkdownJS(sel=...): # -> FT:
    "Implements browser-based markdown rendering."
    ...

def KatexMarkdownJS(sel=..., inline_delim=..., display_delim=..., math_envs=...): # -> tuple[Any, Any]:
    ...

def HighlightJS(sel=..., langs: str | list | tuple = ..., light=..., dark=...): # -> list[FT]:
    "Implements browser-based syntax highlighting. Usage example [here](/tutorials/quickstart_for_web_devs.html#code-highlighting)."
    ...

def SortableJS(sel=..., ghost_class=...): # -> FT:
    ...

